# Generated by Django 6.0.6 on 2026-06-30 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('purchase_in', '采购入库'), ('return_in', '退货入库'), ('check_in', '盘盈入库'), ('sale_out', '销售出库'), ('damage_out', '报损出库'), ('check_out', '盘亏出库')], max_length=20, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('before_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='变动前数量')),
                ('after_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='变动后数量')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productsku', verbose_name='商品SKU')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '库存流水',
                'db_table': 'inventory_record',
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('checking', '盘点中'), ('done', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '盘点单',
                'db_table': 'stock_check',
            },
        ),
    ]
