# Generated by Django 6.0.6 on 2026-07-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_product_image_url'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='系统库存')),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='实盘数量')),
                ('diff_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='差异')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku', verbose_name='商品SKU')),
                ('stock_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcheck', verbose_name='盘点单')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '盘点明细',
                'db_table': 'stock_check_item',
                'unique_together': {('stock_check', 'sku')},
            },
        ),
    ]
