# Generated by Django 6.0.6 on 2026-07-05 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockcheckitem'),
        ('products', '0003_alter_productsku_barcode_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['tenant', 'sku_id', '-created_at'], name='idx_invrec_tenant_sku'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['tenant', 'type', '-created_at'], name='idx_invrec_tenant_type'),
        ),
    ]
