-- Exact column order matching Django migrations
BEGIN;

DROP TABLE IF EXISTS finance_daily_summary CASCADE;
DROP TABLE IF EXISTS employee_shift CASCADE;
DROP TABLE IF EXISTS stock_check CASCADE;
DROP TABLE IF EXISTS inventory_record CASCADE;
DROP TABLE IF EXISTS pos_order_item CASCADE;
DROP TABLE IF EXISTS pos_order CASCADE;
DROP TABLE IF EXISTS product_sku CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS user_tenant CASCADE;
DROP TABLE IF EXISTS auth_permission CASCADE;
DROP TABLE IF EXISTS django_content_type CASCADE;
DROP TABLE IF EXISTS django_migrations CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS tenant CASCADE;

-- 1. tenant
CREATE TABLE tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    slug varchar(50) NOT NULL UNIQUE,
    logo varchar(100),
    address text NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    business_hours varchar(100) NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. user
CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz,
    is_superuser boolean NOT NULL DEFAULT false,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    date_joined timestamptz NOT NULL DEFAULT now(),
    phone varchar(20) NOT NULL DEFAULT '',
    avatar varchar(100)
);

-- 3. user_tenant
CREATE TABLE user_tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar(20) NOT NULL DEFAULT 'cashier',
    joined_at timestamptz NOT NULL DEFAULT now(),
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    UNIQUE (user_id, tenant_id)
);

-- 4. django_content_type
CREATE TABLE django_content_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    UNIQUE (app_label, model)
);

-- 5. django_migrations
CREATE TABLE django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamptz NOT NULL DEFAULT now()
);

-- 6. auth_permission
CREATE TABLE auth_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL DEFAULT '',
    content_type_id bigint NOT NULL REFERENCES django_content_type(id) ON DELETE CASCADE,
    codename varchar(100) NOT NULL,
    UNIQUE (content_type_id, codename)
);

-- 7. product_category
CREATE TABLE product_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    parent_id bigint REFERENCES product_category(id) ON DELETE CASCADE,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 8. product
CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(200) NOT NULL,
    image varchar(100),
    unit varchar(20) NOT NULL DEFAULT '个',
    is_weighted boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    category_id bigint REFERENCES product_category(id) ON DELETE SET NULL,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 9. product_sku
CREATE TABLE product_sku (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    barcode varchar(100) NOT NULL UNIQUE,
    spec_name varchar(200) NOT NULL DEFAULT '默认',
    spec_attrs jsonb NOT NULL DEFAULT '{}',
    purchase_price numeric(10,2) NOT NULL DEFAULT 0,
    selling_price numeric(10,2) NOT NULL DEFAULT 0,
    stock_quantity numeric(12,3) NOT NULL DEFAULT 0,
    stock_alert numeric(12,3) NOT NULL DEFAULT 0,
    product_id bigint NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 10. member
CREATE TABLE member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL,
    phone varchar(20) NOT NULL,
    card_no varchar(50) NOT NULL DEFAULT '',
    points integer NOT NULL DEFAULT 0,
    balance numeric(10,2) NOT NULL DEFAULT 0,
    total_spent numeric(12,2) NOT NULL DEFAULT 0,
    remark text NOT NULL DEFAULT '',
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 11. supplier
CREATE TABLE supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(200) NOT NULL,
    contact varchar(100) NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    address text NOT NULL DEFAULT '',
    remark text NOT NULL DEFAULT '',
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 12. pos_order
CREATE TABLE pos_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    order_no varchar(50) NOT NULL UNIQUE,
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    discount_amount numeric(10,2) NOT NULL DEFAULT 0,
    paid_amount numeric(10,2) NOT NULL DEFAULT 0,
    payment_method varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'completed',
    paid_at timestamptz NOT NULL DEFAULT now(),
    cashier_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    member_id bigint REFERENCES member(id) ON DELETE SET NULL,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 13. pos_order_item
CREATE TABLE pos_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    product_name varchar(200) NOT NULL,
    spec_name varchar(200) NOT NULL DEFAULT '',
    quantity numeric(10,3) NOT NULL,
    price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    order_id bigint NOT NULL REFERENCES pos_order(id) ON DELETE CASCADE,
    sku_id bigint NOT NULL REFERENCES product_sku(id) ON DELETE RESTRICT,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 14. inventory_record
CREATE TABLE inventory_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    type varchar(20) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    before_quantity numeric(12,3) NOT NULL DEFAULT 0,
    after_quantity numeric(12,3) NOT NULL DEFAULT 0,
    remark text NOT NULL DEFAULT '',
    operator_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    sku_id bigint NOT NULL REFERENCES product_sku(id) ON DELETE CASCADE,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 15. stock_check
CREATE TABLE stock_check (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    status varchar(20) NOT NULL DEFAULT 'draft',
    remark text NOT NULL DEFAULT '',
    created_by_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE
);

-- 16. employee_shift
CREATE TABLE employee_shift (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    start_time timestamptz NOT NULL,
    end_time timestamptz,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);

-- 17. finance_daily_summary
CREATE TABLE finance_daily_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    date date NOT NULL,
    total_orders integer NOT NULL DEFAULT 0,
    total_amount numeric(12,2) NOT NULL DEFAULT 0,
    cash_amount numeric(12,2) NOT NULL DEFAULT 0,
    wechat_amount numeric(12,2) NOT NULL DEFAULT 0,
    alipay_amount numeric(12,2) NOT NULL DEFAULT 0,
    member_amount numeric(12,2) NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    UNIQUE (tenant_id, date)
);

COMMIT;
