-- ============================================
-- 安居超市 - Complete Schema
-- Generated from Django models
-- ============================================

BEGIN;

-- 1. tenant
CREATE TABLE IF NOT EXISTS tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    slug varchar(50) NOT NULL UNIQUE,
    logo varchar(100),
    address text NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    business_hours varchar(100) NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. user (quoted - reserved word)
CREATE TABLE IF NOT EXISTS "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz,
    is_superuser boolean NOT NULL DEFAULT false,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    date_joined timestamptz NOT NULL DEFAULT now(),
    phone varchar(20) NOT NULL DEFAULT '',
    avatar varchar(100)
);

-- 3. user_tenant (junction)
CREATE TABLE IF NOT EXISTS user_tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    role varchar(20) NOT NULL DEFAULT 'cashier',
    joined_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, tenant_id)
);

-- 4. django_content_type (needed by seed.sql)
CREATE TABLE IF NOT EXISTS django_content_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    UNIQUE (app_label, model)
);

-- 5. django_migrations (needed by seed.sql)
CREATE TABLE IF NOT EXISTS django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamptz NOT NULL DEFAULT now()
);

-- 6. auth_permission (needed by seed.sql)
CREATE TABLE IF NOT EXISTS auth_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type_id bigint NOT NULL REFERENCES django_content_type(id) ON DELETE CASCADE,
    codename varchar(100) NOT NULL,
    name varchar(255) NOT NULL DEFAULT '',
    UNIQUE (content_type_id, codename)
);

-- 7. product_category
CREATE TABLE IF NOT EXISTS product_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL,
    parent_id bigint REFERENCES product_category(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pcat_tenant_created ON product_category(tenant_id, created_at DESC);

-- 8. product
CREATE TABLE IF NOT EXISTS product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(200) NOT NULL,
    category_id bigint REFERENCES product_category(id) ON DELETE SET NULL,
    image varchar(100),
    unit varchar(20) NOT NULL DEFAULT '个',
    is_weighted boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_product_tenant_created ON product(tenant_id, created_at DESC);

-- 9. product_sku
CREATE TABLE IF NOT EXISTS product_sku (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    product_id bigint NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    barcode varchar(100) NOT NULL,
    spec_name varchar(200) NOT NULL DEFAULT '默认',
    spec_attrs jsonb NOT NULL DEFAULT '{}',
    purchase_price numeric(10,2) NOT NULL DEFAULT 0,
    selling_price numeric(10,2) NOT NULL DEFAULT 0,
    stock_quantity numeric(12,3) NOT NULL DEFAULT 0,
    stock_alert numeric(12,3) NOT NULL DEFAULT 0,
    UNIQUE (barcode)
);
CREATE INDEX IF NOT EXISTS idx_psku_tenant_created ON product_sku(tenant_id, created_at DESC);

-- 10. member
CREATE TABLE IF NOT EXISTS member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL,
    phone varchar(20) NOT NULL,
    card_no varchar(50) NOT NULL DEFAULT '',
    points integer NOT NULL DEFAULT 0,
    balance numeric(10,2) NOT NULL DEFAULT 0,
    total_spent numeric(12,2) NOT NULL DEFAULT 0,
    remark text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_member_tenant_created ON member(tenant_id, created_at DESC);

-- 11. supplier
CREATE TABLE IF NOT EXISTS supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    name varchar(200) NOT NULL,
    contact varchar(100) NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    address text NOT NULL DEFAULT '',
    remark text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_supplier_tenant_created ON supplier(tenant_id, created_at DESC);

-- 12. pos_order
CREATE TABLE IF NOT EXISTS pos_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    order_no varchar(50) NOT NULL UNIQUE,
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    discount_amount numeric(10,2) NOT NULL DEFAULT 0,
    paid_amount numeric(10,2) NOT NULL DEFAULT 0,
    payment_method varchar(20) NOT NULL,
    member_id bigint REFERENCES member(id) ON DELETE SET NULL,
    cashier_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'completed',
    paid_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_posorder_tenant_created ON pos_order(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posorder_paid_at ON pos_order(paid_at DESC);

-- 13. pos_order_item
CREATE TABLE IF NOT EXISTS pos_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    order_id bigint NOT NULL REFERENCES pos_order(id) ON DELETE CASCADE,
    sku_id bigint NOT NULL REFERENCES product_sku(id) ON DELETE RESTRICT,
    product_name varchar(200) NOT NULL,
    spec_name varchar(200) NOT NULL DEFAULT '',
    quantity numeric(10,3) NOT NULL,
    price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_positem_tenant_created ON pos_order_item(tenant_id, created_at DESC);

-- 14. inventory_record
CREATE TABLE IF NOT EXISTS inventory_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    sku_id bigint NOT NULL REFERENCES product_sku(id) ON DELETE CASCADE,
    type varchar(20) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    before_quantity numeric(12,3) NOT NULL DEFAULT 0,
    after_quantity numeric(12,3) NOT NULL DEFAULT 0,
    remark text NOT NULL DEFAULT '',
    operator_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_ir_tenant_created ON inventory_record(tenant_id, created_at DESC);

-- 15. stock_check
CREATE TABLE IF NOT EXISTS stock_check (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    status varchar(20) NOT NULL DEFAULT 'draft',
    remark text NOT NULL DEFAULT '',
    created_by_id bigint NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sc_tenant_created ON stock_check(tenant_id, created_at DESC);

-- 16. employee_shift
CREATE TABLE IF NOT EXISTS employee_shift (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    start_time timestamptz NOT NULL,
    end_time timestamptz
);
CREATE INDEX IF NOT EXISTS idx_es_tenant_created ON employee_shift(tenant_id, created_at DESC);

-- 17. finance_daily_summary
CREATE TABLE IF NOT EXISTS finance_daily_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    date date NOT NULL,
    total_orders integer NOT NULL DEFAULT 0,
    total_amount numeric(12,2) NOT NULL DEFAULT 0,
    cash_amount numeric(12,2) NOT NULL DEFAULT 0,
    wechat_amount numeric(12,2) NOT NULL DEFAULT 0,
    alipay_amount numeric(12,2) NOT NULL DEFAULT 0,
    member_amount numeric(12,2) NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, date)
);
CREATE INDEX IF NOT EXISTS idx_fds_tenant_created ON finance_daily_summary(tenant_id, created_at DESC);

COMMIT;
