# Generated by Django 6.0.6 on 2026-06-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='营业额')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='现金收款')),
                ('wechat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='微信收款')),
                ('alipay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='支付宝收款')),
                ('member_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='会员卡收款')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '日结汇总',
                'db_table': 'finance_daily_summary',
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
