# Generated by Django 6.0.6 on 2026-06-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('card_no', models.CharField(blank=True, default='', max_length=50, verbose_name='会员卡号')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='储值余额')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计消费')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '会员',
                'db_table': 'member',
                'ordering': ['-created_at'],
            },
        ),
    ]
