# Generated by Django 6.0.6 on 2026-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='令牌创建时间'),
        ),
    ]
