# Generated by Django 6.0.6 on 2026-07-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_hash_existing_passwords'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', help_text='哈希密码，禁止在 API 响应中暴露', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(blank=True, default='', help_text='哈希令牌，禁止在 API 响应中暴露', max_length=128, verbose_name='登录令牌'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tenant', 'token'], name='idx_member_tenant_token'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uq_member_tenant_phone'),
        ),
    ]
