# Generated by Django 6.0.6 on 2026-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='broadcast_active',
            field=models.BooleanField(default=False, verbose_name='广播启用'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='broadcast_message',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='广播内容'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='broadcast_severity',
            field=models.CharField(choices=[('info', '通知'), ('warning', '注意'), ('error', '紧急')], default='warning', max_length=10, verbose_name='广播级别'),
        ),
    ]
