# Generated by Django 6.0.6 on 2026-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_broadcast_active_tenant_broadcast_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='footer_text',
            field=models.TextField(blank=True, default='', verbose_name='页脚文字'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paper_width',
            field=models.CharField(choices=[('58', '58mm'), ('80', '80mm')], default='58', max_length=3, verbose_name='纸张宽度'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='print_barcode',
            field=models.BooleanField(default=True, verbose_name='打印条码'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='print_logo',
            field=models.BooleanField(default=True, verbose_name='打印Logo'),
        ),
    ]
