# Generated by Django 6.0.6 on 2026-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='spec_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='规格'),
        ),
    ]
