# Generated by Django 6.0.6 on 2026-07-05 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_password_alter_member_token_and_more'),
        ('pos', '0003_alter_order_cashier'),
        ('products', '0003_alter_productsku_barcode_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', '-paid_at'], name='idx_order_tenant_paid'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'payment_method'], name='idx_order_tenant_pay'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'member_id'], name='idx_order_tenant_member'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'sku_id'], name='idx_orderitem_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_order_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='chk_order_paid_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='chk_order_discount_nonneg'),
        ),
    ]
