# Generated by Django 6.0.6 on 2026-07-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_hash_existing_passwords'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('discount_type', models.CharField(choices=[('fixed', '满减'), ('percent', '折扣')], default='fixed', max_length=10, verbose_name='类型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('total_count', models.IntegerField(default=100, verbose_name='发行数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已领取')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='过期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='MemberCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='券码')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon', verbose_name='优惠券')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='members.member', verbose_name='会员')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '会员优惠券',
                'db_table': 'member_coupon',
                'unique_together': {('member', 'coupon')},
            },
        ),
    ]
