# Generated by Django 6.0.6 on 2026-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0003_alter_productsku_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='不选则全场通用', to='products.category', verbose_name='适用品类'),
        ),
    ]
