# Generated by Django 6.0.6 on 2026-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='勾选后只有无任何订单历史的会员能用', verbose_name='仅限首单'),
        ),
    ]
