# Generated by Django 6.0.6 on 2026-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='barcode',
            field=models.CharField(max_length=100, verbose_name='条码'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='uq_tenant_barcode'),
        ),
    ]
