# Generated by Django 6.0.6 on 2026-07-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsku_barcode_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent_id'], name='idx_category_tenant_parent'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='chk_sku_purchase_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='chk_sku_selling_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='chk_sku_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.CheckConstraint(condition=models.Q(('stock_alert__gte', 0)), name='chk_sku_alert_nonneg'),
        ),
    ]
